
project_id = "zvngmdqdwaznpsqvwcod"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true

[functions.cv-analysis]
verify_jwt = true

[functions.linkedin-generator]
verify_jwt = true

[functions.ats-optimization]
verify_jwt = true

[functions.interview-analysis]
verify_jwt = true

[functions.question-generator]
verify_jwt = true
