// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvngmdqdwaznpsqvwcod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2bmdtZHFkd2F6bnBzcXZ3Y29kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NjI1NjEsImV4cCI6MjA2ODIzODU2MX0.pvCfBJMRAlWPxEXo9B62r-YLPcK1mQgi05SYSeBew-w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});