name: Feature Branch Validation

on:
  pull_request:
    branches: [develop]
    types: [opened, synchronize, reopened]

jobs:
  validate-feature:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Validate feature flags
        run: |
          echo "Validating feature flag usage"
          grep -r "isFeatureEnabled\|FeatureGate" src/ || true
          
      - name: Check for security patterns
        run: |
          echo "Checking for security anti-patterns"
          grep -r "dangerouslySetInnerHTML" src/ && exit 1 || echo "No unsafe HTML patterns found"
          
      - name: Build with feature flags
        run: npm run build
        env:
          VITE_ENABLE_WHITE_LABEL: 'true'
          VITE_ENABLE_ADVANCED_ANALYTICS: 'true'
          VITE_ENABLE_BETA_FEATURES: 'true'
          
  integration-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup test environment
        run: echo "Setup integration testing environment"
        
      - name: Run integration tests
        run: echo "Run feature integration tests"
        # Add your integration test commands here